/**
 * Issue #54 — Egypt National ID (الرقم القومي) validation, parsing & coverage.
 *
 * Scope: add EGY support following the country-module + registry pattern, with
 * an HONEST checksum contract (format + semantic by default; opt-in, UNVERIFIED
 * Luhn via { strictChecksum: true }). Target branch coverage >= 80%.
 *
 * Checksum note: Egypt publishes no official check-digit algorithm. The Luhn
 * vectors below are SELF-CONSISTENT (generated by the same checksum() helper)
 * and are used only to exercise the opt-in strict path — they are NOT a claim
 * that Luhn is the official Egyptian algorithm. See docs/research/egypt-national-id.md.
 *
 * Synthetic-data notice: every ID below is synthetic, constructed only to
 * exercise validation. None is a knowingly-real personal identifier.
 *
 * Issue: https://github.com/identique/idnumbers-npm/issues/54
 */

import { validate, parse, checksum, METADATA, GOVERNORATES } from '../countries/egy/nationalId';
import { NationalID } from '../countries/egy';
import { Gender } from '../constants';
import { validateNationalId, parseIdInfo, getCountryIdFormat } from '../index';

// Strict-valid (also Luhn-valid) synthetic IDs: CYYMMDDGGSSSSV
const VALID_STRICT = [
  '29001010101231', // 1990-01-01, Cairo (01),       sn 0123 -> MALE
  '30503123456789', // 2005-03-12, North Sinai (34), sn 5678 -> FEMALE
  '28512258899998', // 1985-12-25, Born abroad (88),  sn 9999 -> MALE
  '21207142104567', // 1912-07-14, Giza (21),         sn 0456 -> FEMALE
];

describe('Egypt (EGY) — National ID', () => {
  describe('METADATA', () => {
    it('exposes the expected static metadata', () => {
      expect(METADATA.iso3166Alpha2).toBe('EG');
      expect(METADATA.minLength).toBe(14);
      expect(METADATA.maxLength).toBe(14);
      expect(METADATA.isParsable).toBe(true);
      // Default behaviour is format-only; checksum is opt-in & unverified.
      expect(METADATA.hasChecksum).toBe(false);
      expect(METADATA.displayFormat).toBe('CYYMMDDGGSSSSV');
    });

    it('ships a self-validating example', () => {
      expect(validate(METADATA.example)).toBe(true);
      expect(validate(METADATA.example, { strictChecksum: true })).toBe(true);
    });

    it('exposes the same surface via the NationalID object', () => {
      expect(NationalID.METADATA).toBe(METADATA);
      expect(NationalID.validate(METADATA.example)).toBe(true);
      expect(NationalID.parse(METADATA.example)).not.toBeNull();
      expect(NationalID.checksum(METADATA.example)).toBe(1);
    });
  });

  describe('validate() — format & semantics', () => {
    test.each(VALID_STRICT)('accepts valid ID %s', id => {
      expect(validate(id)).toBe(true);
    });

    it('accepts a real leap-day birth date (2000-02-29)', () => {
      expect(validate('30002290100010')).toBe(true);
    });

    const invalidFormat: Array<[string, string]> = [
      ['', 'empty string'],
      ['2900101010123', '13 digits (too short)'],
      ['290010101012388', '15 digits (too long)'],
      ['2900101010123X', 'non-digit character'],
      ['19001010101238', 'century digit 1 (unsupported)'],
      ['49001010101238', 'century digit 4 (unsupported)'],
      ['29013010101238', 'month 13'],
      ['29000110101238', 'month 00'],
      ['29001320101238', 'day 32'],
      ['29001000101238', 'day 00'],
    ];
    test.each(invalidFormat)('rejects %s — %s', id => {
      expect(validate(id)).toBe(false);
    });

    it('rejects a non-existent leap day (2099-02-29, not a leap year)', () => {
      expect(validate('39902290100456')).toBe(false);
    });

    it('rejects an unknown governorate code (99)', () => {
      expect(validate('29001019901238')).toBe(false);
    });

    it('accepts every known governorate code', () => {
      for (const code of Object.keys(GOVERNORATES)) {
        // CYYMMDD=2900101 (1990-01-01), GG=code, SSSS=0123, V=0
        const candidate = `2900101${code}01230`;
        expect(candidate).toHaveLength(14);
        expect(validate(candidate)).toBe(true);
      }
    });
  });

  describe('validate() — opt-in Luhn checksum', () => {
    test.each(VALID_STRICT)('strict mode accepts checksum-valid %s', id => {
      expect(validate(id, { strictChecksum: true })).toBe(true);
    });

    it('strict mode rejects a wrong check digit that format-only accepts', () => {
      const wrong = '29001010101230'; // correct check digit is 1
      expect(validate(wrong)).toBe(true);
      expect(validate(wrong, { strictChecksum: true })).toBe(false);
    });
  });

  describe('checksum()', () => {
    it('returns the Luhn check digit for a well-formed ID', () => {
      expect(checksum('29001010101231')).toBe(1);
    });

    it('returns null for a malformed ID', () => {
      expect(checksum('not-an-id')).toBeNull();
      expect(checksum('2900101010123')).toBeNull();
    });
  });

  describe('parse()', () => {
    it('extracts birth date, gender, governorate and serial', () => {
      const info = parse('29001010101231');
      expect(info).not.toBeNull();
      expect(info!.isValid).toBe(true);
      expect(info!.birthDate.getFullYear()).toBe(1990);
      expect(info!.birthDate.getMonth()).toBe(0); // January
      expect(info!.birthDate.getDate()).toBe(1);
      expect(info!.gender).toBe(Gender.MALE);
      expect(info!.governorateCode).toBe('01');
      expect(info!.governorate).toBe('Cairo');
      expect(info!.serialNumber).toBe('0123');
      expect(info!.checksum).toBe(1);
      expect(typeof info!.age).toBe('number');
    });

    it('resolves the 2000s century and female gender', () => {
      const info = parse('30503123456789');
      expect(info).not.toBeNull();
      expect(info!.birthDate.getFullYear()).toBe(2005);
      expect(info!.gender).toBe(Gender.FEMALE);
      expect(info!.governorate).toBe('North Sinai');
    });

    it('maps the born-abroad governorate code (88)', () => {
      const info = parse('28512258899998');
      expect(info!.governorateCode).toBe('88');
      expect(info!.governorate).toBe('Born outside Egypt');
    });

    it('returns null for malformed, bad-date and unknown-governorate inputs', () => {
      expect(parse('')).toBeNull();
      expect(parse('2900101010123')).toBeNull(); // too short
      expect(parse('39902290100456')).toBeNull(); // 2099-02-29 invalid
      expect(parse('29001019901238')).toBeNull(); // governorate 99
    });
  });

  describe('registry dispatch', () => {
    it('validates via validateNationalId for EGY and the EG alias', () => {
      expect(validateNationalId('EGY', METADATA.example).isValid).toBe(true);
      expect(validateNationalId('EG', METADATA.example).isValid).toBe(true);
      expect(validateNationalId('EGY', '29001010101').isValid).toBe(false);
    });

    it('dispatched validation is format-only (does not enforce checksum)', () => {
      // Correct check digit is 1; a wrong digit still passes default dispatch.
      expect(validateNationalId('EGY', '29001010101230').isValid).toBe(true);
    });

    it('parses via parseIdInfo', () => {
      const info = parseIdInfo('EGY', METADATA.example);
      expect(info).toBeTruthy();
      expect(info.gender).toBe(Gender.MALE);
      expect(info.governorate).toBe('Cairo');
    });

    it('exposes format info via getCountryIdFormat', () => {
      const fmt = getCountryIdFormat('EGY');
      expect(fmt).toBeTruthy();
      expect(fmt!.countryCode).toBe('EGY');
      expect(fmt!.length).toEqual({ min: 14, max: 14 });
      expect(fmt!.isParsable).toBe(true);
      expect(fmt!.hasChecksum).toBe(false);
    });
  });
});
